name: Build LiveSplit.DynamicLayout

on:
  push:
    branches: [ mster ]
  pull_request:
    branches: [ mster ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Mono
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore LiveSplit.DynamicLayout.sln

    - name: Build Solution
      run: msbuild LiveSplit.DynamicLayout.sln -p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DynamicLayout-DLL
        path: bin/Release/LiveSplit.DynamicLayout.dll
      with:
        name: DynamicLayout-DLL
        path: bin/Release/LiveSplit.DynamicLayout.dll
