name: Build LiveSplit.DynamicLayout

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    - name: Install .NET Framework 4.8 Developer Pack
      run: |
        curl -L -o dotnet461-devpack.exe https://dotnet.microsoft.com/fr-fr/download/dotnet-framework/thank-you/net48-developer-pack-offline-installer
        .\dotnet461-devpack.exe /quiet /norestart
      shell: cmd

    - name: Restore NuGet Packages
      run: nuget restore LiveSplit.DynamicLayout.sln

    - name: Build Solution
      run: msbuild LiveSplit.DynamicLayout.sln -p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DynamicLayout-DLL
        path: bin/Release/LiveSplit.DynamicLayout.dll
